plugins {
    id 'com.android.application'
}

android {
    namespace 'at.pardus.android.browser'
    compileSdk 34
    defaultConfig {
        applicationId "at.pardus.android.browser"
        minSdk 26
        targetSdk 34
        versionCode 26163
        versionName '1.6.3'
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        lintConfig = file('lint.xml')
    }
}

dependencies {
    implementation 'at.pardus.android:webview-gm-lib:1.2.0'
    implementation 'at.pardus.android:webview-gm-ui:1.2.0'
    implementation 'org.nanohttpd:nanohttpd-webserver:2.3.1'
}
